blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogPostListView,
    BlogPostCreateView,
    BlogPostDeleteView,
    BlogPostDetailView,
    BlogPostUpdateView,
    blog_main,
)

app_name = BlogConfig.name
urlpatterns = [
    path("blogpost_list/", BlogPostListView.as_view(), name="blogpost_list"),
    path("post/<int:pk>/", BlogPostDetailView.as_view(), name="post"),
    path("blogpost_create/", BlogPostCreateView.as_view(), name="blogpost_create"),
    path("blogpost_update/<int:pk>/", BlogPostUpdateView.as_view(), name="blogpost_update"),
    path("blogpost_delete/<int:pk>/", BlogPostDeleteView.as_view(), name="blogpost_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("mailing.urls", namespace="home")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import (
    home,
    MessageListView,
    MessageDetailView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
    ClientListView,
    ClientDetailView,
    ClientUpdateView,
    ClientDeleteView,
    ClientCreateView,
    MailingListView,
    MailingDetailView,
    MailingCreateView,
    MailingUpdateView,
    MailingDeleteView,
)

app_name = MailingConfig.name
urlpatterns = [
    path("", home, name="home"),

    path("mailing_list/", MailingListView.as_view(), name="mailing_list"),
    path("mailing/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing_create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing_edit/<int:pk>/", MailingUpdateView.as_view(), name="mailing_update"),
    path(
        "mailing_delete/<int:pk>/", MailingDeleteView.as_view(), name="mailing_delete"
    ),

    path("message_list/", MessageListView.as_view(), name="message_list"),
    path(
        "message/<int:pk>/", cache_page(60)(MessageDetailView.as_view()), name="message"
    ),
    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "message_edit/<int:pk>/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "message_delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"
    ),

    path("client_list/", ClientListView.as_view(), name="client_list"),
    path("client/<int:pk>/", cache_page(60)(ClientDetailView.as_view()), name="client"),
    path("client_create/", ClientCreateView.as_view(), name="client_create"),
    path("client_edit/<int:pk>/", ClientUpdateView.as_view(), name="client_update"),
    path("client_delete/<int:pk>/", ClientDeleteView.as_view(), name="client_delete"),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from users.views import (
    UserCreateView,
    email_verification,
    UserResetPasswordView,
    NotMailPageView,
)

# from django.views.decorators.cache import cache_page

from users.apps import UserConfig


app_name = UserConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("reset-password/", UserResetPasswordView.as_view(), name="reset_password"),
    path("not-mail/", NotMailPageView.as_view(), name="not_mail"),
]

mailing/models.py
from django.db import models
from users.models import User


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name="Тема")
    letter_body = models.TextField(
        verbose_name="Описание категории", blank=True, null=True
    )
    owner = models.ForeignKey(
        User, verbose_name="Владелец", blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
        return f"{self.title}"


class Client(models.Model):
    email = models.EmailField(max_length=100, verbose_name="Email")
    client_name = models.TextField(verbose_name="ФИО клиента", blank=True, null=True)
    owner = models.ForeignKey(
        User, verbose_name="Владелец", blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"

    def __str__(self):
        return f"{self.email}"


class Mailing(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование рассылки")
    message = models.ForeignKey(
        Message,
        on_delete=models.SET_NULL,
        verbose_name="Сообщение",
        blank=True,
        null=True,
        related_name="Сообщение",
    )
    created_at = models.DateField(
        auto_now_add=True, verbose_name="Дата создания рассылки"
    )
    owner = models.ForeignKey(
        User, verbose_name="Владелец", blank=True, null=True, on_delete=models.SET_NULL
    )
    send_date = models.DateField(
        verbose_name="Дата начала рассылки", blank=True, null=True
    )
    next_send_date = models.DateField(
        verbose_name="Дата повтора рассылки", blank=True, null=True
    )
    is_active = models.BooleanField(default=True)

    COMPLETED = "completed"
    CREATED = "created"
    STARTED = "started"
    DAY = "once a day"
    MINUTE = "once a minute"
    WEEK = "once a week"
    MONTH = "once a month"
    STATUS = [(COMPLETED, "completed"), (CREATED, "created"), (STARTED, "started")]
    INTERVAL = [
        (DAY, "once a days"),
        (WEEK, "once a week"),
        (MONTH, "once a months"),
    ]
    status = models.CharField(
        choices=STATUS, default=CREATED, verbose_name="Статус рассылки"
    )
    periodicity = models.CharField(
        choices=INTERVAL, default=DAY, verbose_name="Периодичность"
    )
    end_date = models.DateTimeField(
        verbose_name="Дата окончания рассылки",
        blank=True,
        null=True,
    )

    client_list = models.ManyToManyField(Client, related_name="mailing_list")

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ["name", "created_at", "status", "periodicity"]
        permissions = [
            # ('can_view_mailing', 'Может просматривать рассылку'),
            # ('can_disable_mailing', 'Может отключать рассылку')
        ]

    def __str__(self):
        return f"{self.name}"


class Effort(models.Model):
    SUCCESS = "success"
    FAIL = "fail"
    STATUSES = [(SUCCESS, "success"), (FAIL, "fail")]
    last_try = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата попытки рассылки"
    )
    status = models.CharField(choices=STATUSES, default=SUCCESS, verbose_name="Статус")
    response = models.TextField(verbose_name="Ответ", blank=True, null=True)
    mailing = models.ForeignKey(
        Mailing,
        on_delete=models.CASCADE,
        related_name="mailings",
        verbose_name="Рассылка",
    )

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылок"
        ordering = ("status",)

    def __str__(self):
        return f"{self.status}"

mailing/forms.py
from django.forms import BooleanField, ModelForm
from mailing.models import Mailing, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class MailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

    # class ClientForm(StyleFormMixin, forms.ModelForm):
    #     class Meta:
    #         model = Client
    #         fields = '__all__'


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from mailing.forms import MailingForm, ClientForm, MessageForm
from mailing.models import Message, Client, Mailing


def home(request):
    return render(request, "mailing/home.html")


def contacts(request):
    return render(request, "mailing/contacts.html")


class MessageCreateView(CreateView, LoginRequiredMixin):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")


class MessageListView(ListView):
    model = Message


class MessageDetailView(DetailView):
    model = Message


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")


class MessageDeleteView(DeleteView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")


class ClientCreateView(CreateView, LoginRequiredMixin):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")


class ClientListView(ListView):
    model = Client


class ClientDetailView(DetailView):
    model = Client
    form_class = ClientForm


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy("mailing:client_list")


class MailingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    permission_required = "mailing.add_mailing"
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.user = user
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    permission_required = "mailing.change_mailing"
    success_url = reverse_lazy("mailing:mailing_list")


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    # permission_required = 'mailing.view_mailing'

    # def get_context(self, request):
    #     context = super(LivreDesc, self).get_context(request)
    #     context['nb_livres'] = LivreDesc.objects.all().count()
    #     return context

    # def get_context_data(self, *args, **kwargs):
    #     context_data = super().get_context_data(*args, **kwargs)
    #     for mailing in context_data['mailing_list']:
    #         active_version = Mailing.objects.filter(is_active=True)
    #         if active_version:
    #             mailing.active_version = active_version.last().name_version
    #         else:
    #             product.active_version = 'Отсутствует'
    #     return context_data


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    form_class = MailingForm


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Mailing
    permission_required = "mailing.delete_mailing"
    success_url = reverse_lazy("mailing:mailing_list")

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/main.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6">
      <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
          <p class="card-text">Вы хотите удалить {{ object.email }}? </p>
          <div class="card-body">
            {% csrf_token %}
          </div>
          <button type="submit" class="btn btn-primary">Удалить</button>
          <a class="btn btn-primary" href="{% url 'catalog:client_list' %}" role="button">Отмена</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/main.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for client in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{ client.email | truncatechars:100 }} </p>
              <p class="card-text">{{ client.client_name | truncatechars:100 }} </p>

              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if user == client.owner %}
                    <a class="btn btn-primary" href="{% url 'mailing:client_update' client.pk %}" role="button">Редактировать</a>
                    {% endif %}
                  <a class="btn btn-primary" href="{% url 'mailing:client' client.pk %}" role="button">Подробная информация</a>

                  <a class="btn btn-primary" href="{% url 'mailing:client_delete' client.pk %}" role="button">Удалить</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

mailing/templates/mailing/home.html
{% extends 'blog/blogpost_main_page.html' %}
{% load my_tags %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/main.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6">
      <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
          <p class="card-text">Вы хотите удалить {{ object.name }}? </p>
          <div class="card-body">
            {% csrf_token %}
          </div>
          <button type="submit" class="btn btn-primary">Удалить</button>
          <a class="btn btn-primary" href="{% url 'mailing:mailing_list' %}" role="button">Отмена</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/main.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for prod in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ prod.preview | media_filter}}">
            <div class="card-body">
              <p class="card-text">{{ prod.name | truncatechars:100 }} </p>
              <p class="card-text"> Просмотров:</p>
               <p class="card-footer">
                    </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if user == prod.owner %}
                    <a class="btn btn-primary" href="{% url 'mailing:mailing_detail' prod.pk %}" role="button">Редактировать</a>
                    {% endif %}
                  <a class="btn btn-primary" href="{% url 'mailing:mailing_detail' prod.pk %}" role="button">Подробная информация</a>

                  <a class="btn btn-primary" href="{% url 'mailing:mailing_delete' prod.pk %}" role="button">Удалить</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

mailing/templates/mailing/main.html
{% load static %}
{% load my_tags %}
<!doctype html>

<html lang="en" data-bs-theme="auto">
  <head><script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=JjdYlsU7pghciAbaFVn0YX_Aa5BUS35atI6Y7eSawmy7FpYJMEjL7rxgCVzlm4h6cc57KqttVKmDlikO6HXXoERE6oiaYQFlnAoXZx30NR8" charset="UTF-8"></script><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Марк Отто, Джейкоб Торнтон и контрибьюторы Bootstrap">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Таланцев М. Курсовая 6. Основы веб-разработки на Django</title>

    <link rel="canonical" href="https://getbootstrap.su/docs/5.3/examples/album/">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="icon" href="data:;base64,=">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>


  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<header data-bs-theme="dark">
{% include 'mailing/includes/inc_menu.html' %}
</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-12 col-md-8 mx-auto">
        <h1 class="fw-light">Сервис для рассылки сообщений</h1>
        {% if user.is_authenticated %}
        <p>
          <a href="/mailing_list/" class="btn btn-primary my-2">Перейти к списку рассылок</a>
           <a href="/message_list/" class="btn btn-primary my-2">Перейти к списку Сообщений</a>
           <a href="/client_list/" class="btn btn-primary my-2">Перейти к списку клиентов</a>
        </p>
        <p>
          <a href="{% url 'mailing:mailing_create' %}" class="btn btn-primary my-2">Создать рассылку</a>
          <a href="{% url 'mailing:message_create' %}" class="btn btn-primary my-2">Создать Сообщение</a>
          <a href="{% url 'mailing:client_create' %}" class="btn btn-primary my-2">Создать клиента</a>
        </p>
        <p>
          <a href="{% url 'users:logout' %}" class="btn btn-secondary my-2">Выход</a>
        </p>
        {% else %}
        <p>
            <a href="{% url 'users:login' %}" class="btn btn-primary my-2">Вход</a>
            <a href="{% url 'users:register' %}" class="btn btn-primary my-2">Регистрация</a>
        </p>
        {% endif %}


      </div>
    </div>
  </section>

{% block content %}

{% endblock %}

</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Вернуться наверх</a>
    </p>
    <p class="mb-1">Пример альбома &copy; Bootstrap, но, пожалуйста, скачайте и настройте его под себя!</p>
    <p class="mb-0">Новое в Bootstrap? <a href="/">Посетите домашнюю страницу</a> или прочтите наше <a href="/docs/5.3/getting-started/introduction/">руководство по началу работы</a>.</p>
  </div>
</footer>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

    </body>
</html>

mailing/templates/mailing/message_list.html
{% extends 'mailing/main.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for message in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{ message.title | truncatechars:100 }} </p>
              <p class="card-text">{{ message.letter_body | truncatechars:100 }} </p>

              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if user == message.owner %}
                    <a class="btn btn-primary" href="{% url 'mailing:message_update' message.pk %}" role="button">Редактировать</a>

                  <a class="btn btn-primary" href="{% url 'mailing:message' message.pk %}" role="button">Подробная информация</a>
                  <a class="btn btn-primary" href="{% url 'mailing:message_delete' message.pk %}" role="button">Удалить</a>
                    {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}