blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogPostListView,
    BlogPostCreateView,
    BlogPostDeleteView,
    BlogPostDetailView,
    BlogPostUpdateView,
    blog_main,
)

app_name = BlogConfig.name
urlpatterns = [
    path("blogpost_list/", BlogPostListView.as_view(), name="blogpost_list"),
    path("post/<int:pk>/", BlogPostDetailView.as_view(), name="post"),
    path("blogpost_create/", BlogPostCreateView.as_view(), name="blogpost_create"),
    path("blogpost_update/<int:pk>/", BlogPostUpdateView.as_view(), name="blogpost_update"),
    path("blogpost_delete/<int:pk>/", BlogPostDeleteView.as_view(), name="blogpost_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("mailing.urls", namespace="home")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class BlogPost(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name="содержимое", blank=True, null=True)
    preview = models.ImageField(
        upload_to="blog/image",
        blank=True,
        null=True,
        verbose_name="превью (изображение)",
    )
    created_at = models.DateField(
        auto_now_add=True, verbose_name="Дата создания (записи в БД)"
    )
    publication = models.BooleanField(verbose_name="Публикация поста")

    views_counter = models.PositiveIntegerField(
        verbose_name="Счётчик просмотров",
        help_text="Проказывает кол-во просмотров",
        default=0,
    )

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["title", "slug", "publication"]

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from pytils.translit import slugify

from blog.models import BlogPost


def blog_main(request):
    return render(request, "blog/blogpost_main_page.html")


class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication=True)
        return queryset


class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class BlogPostCreateView(CreateView):
    model = BlogPost
    fields = ("title", "description", "preview", "publication")
    success_url = reverse_lazy("blog:blogpost_list")

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ("title", "description", "preview", "publication")
    success_url = reverse_lazy("blog:blogpost_list")

    def get_success_url(self):
        return reverse("blog:post", args=[self.kwargs.get("pk")])


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy("blog:blogpost_list")

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'blog/blogpost_main_page.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6">
      <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
          <p class="card-text">Вы хотите удалить {{ object.name }}? </p>
          <div class="card-body">
            {% csrf_token %}
          </div>
          <button type="submit" class="btn btn-primary">Удалить</button>
          <a class="btn btn-primary" href="{% url 'blog:blogpost_list' %}" role="button">Отмена</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'blog/blogpost_main_page.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ object.preview | media_filter }}">
            <div class="card-body">
              <p class="card-text">{{ object.title | truncatechars:20 }} </p>
              <p class="card-text">{{ object.slug }} </p>
              <p class="card-text">{{ object.description }} </p>

              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'blog:blogpost_list' %}" role="button">Назад</a>
                </div>
                <small class="text-body-secondary">Просмотров: {{ object.views_counter }}</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'blog/blogpost_main_page.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6">
      <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
          <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
          <button type="submit" class="btn btn-primary">
            {% if object %}
            Сохранить
            {% else %}
            Создать
            {% endif %}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'mailing/main.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for post in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ post.preview | media_filter}}">
            <div class="card-body">
              <p class="card-text">{{ post.title | truncatechars:100 }} </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'blog:post' post.pk %}" role="button">Подробная информация</a>
                  <a class="btn btn-primary" href="{% url 'blog:blogpost_update' post.pk %}" role="button">Редактировать</a>
                  <a class="btn btn-primary" href="{% url 'blog:blogpost_delete' post.pk %}" role="button">Удалить</a>
                </div>

              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/blogpost_main_page.html
{% extends 'blog/blogpost_list.html' %}
{% load my_tags %}

{% block content %}
<div class="row text-center">
    <div class="col-3">
        <li>Количество рассылок - {{ number_mailing }}</li>
        <li>Количество активных рассылок - {{ number_of_active_mailing }}</li>
        <li>Уникальные клиенты рассылок - {{ number_customer }}</li>
    </div>
</div>
<div class="row text-center">
{% for blog in object_list %}
    {% if blog.pk == first_record or blog.pk == second_record or blog.pk == third_record %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <img src="{{ blog.picture | media_filter }}" width="200" height="160">
                <h4 class="my-0 font-weight-normal">{{ blog.heading }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>{{ blog.content_of_article }}</li>
                    <li>{{ blog.number_of_views }}</li>
                    <li>{{ blog.date_of_publication }}</li>
                </ul>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}